<?
$def = array(
	"name" => "usradmin",
	"type" => "standard",
	"description" => "usradmin",
	"files" => array(
		"0" => "inc/etc/access/usradmin.access",
		"1" => "inc/etc/form/mod_usradmin_grp.form",
		"2" => "inc/etc/form/mod_usradmin_usr.form",
		"3" => "inc/etc/form/mod_usradmin_usr_online.form",
		"4" => "inc/etc/instance/usradmin.instance",
		"5" => "inc/mods/usradmin/class_usradminAction.inc.php",
		"6" => "inc/mods/usradmin/class_usradminView.inc.php",
		"7" => "inc/rsc/def/usradmin.def",
		"8" => "inc/rsc/sql/data/usradmin.mm_usradmin_usr.grp.sql",
		"9" => "inc/rsc/sql/data/usradmin.mod_usradmin_grp.sql",
		"10" => "inc/rsc/sql/data/usradmin.mod_usradmin_usr.sql",
		"11" => "inc/rsc/sql/tbl/usradmin.mm_usradmin_usr.grp.sql",
		"12" => "inc/rsc/sql/tbl/usradmin.mod_usradmin_grp.sql",
		"13" => "inc/rsc/sql/tbl/usradmin.mod_usradmin_usr.sql",
		"14" => "web/system/img/icons/icon_mod_usradmin_grp.gif",
		"15" => "web/system/img/icons/icon_mod_usradmin_usr.gif",
		"16" => "web/tpl/hundertelf/usradmin/grp_form.tpl",
		"17" => "web/tpl/hundertelf/usradmin/grp_list.tpl",
		"18" => "web/tpl/hundertelf/usradmin/register_complete.tpl",
		"19" => "web/tpl/hundertelf/usradmin/register_form.tpl",
		"20" => "web/tpl/hundertelf/usradmin/register_sentmail.tpl",
		"21" => "web/tpl/hundertelf/usradmin/register_senttext.tpl",
		"22" => "web/tpl/hundertelf/usradmin/usr_form.tpl",
		"23" => "web/tpl/hundertelf/usradmin/usr_home_guest.tpl",
		"24" => "web/tpl/hundertelf/usradmin/usr_home_others_new.tpl",
		"25" => "web/tpl/hundertelf/usradmin/usr_home_self_new.tpl",
		"26" => "web/tpl/hundertelf/usradmin/usr_list.tpl",
		"27" => "web/tpl/hundertelf/usradmin/usr_profile_new.tpl",
		"28" => "web/tpl/hundertelf/usradmin/usr_search.tpl",
	),
	"folders" => array(
	),
	"events" => array(
	),
	"views" => array(
	),
	"author" => "hundertelf,Thomas Schindler,Joachim Klinkhammer,Oli Blum",
	"email" => "development@hundertelf.com",
	"date" => "2004",
	"version" => "10.1",
);
?>
