<?
$def = array(
	"name" => "page",
	"type" => "standard",
	"description" => "page",
	"files" => array(
		"0" => "inc/etc/access/page.access",
		"1" => "inc/etc/acl/mod_page.acl",
		"2" => "inc/etc/form/mod_level_page.form",
		"3" => "inc/etc/form/mod_new_page.form",
		"4" => "inc/etc/form/mod_page.form",
		"5" => "inc/etc/form/mod_page_tpl.form",
		"6" => "inc/etc/instance/page.instance",
		"7" => "inc/mods/err_pages/class_err_pagesAction.inc.php",
		"8" => "inc/mods/err_pages/class_err_pagesView.inc.php",
		"9" => "inc/mods/page/class_pageAction.inc.php",
		"10" => "inc/mods/page/class_pageView.inc.php",
		"11" => "inc/rsc/def/err_pages.def",
		"12" => "inc/rsc/def/page.def",
		"13" => "inc/rsc/sql/data/page.mod_page.sql",
		"14" => "inc/rsc/sql/data/page.mod_page_acl.sql",
		"15" => "inc/rsc/sql/data/page.mod_page_mod_usr_ar.sql",
		"16" => "inc/rsc/sql/data/page.mod_page_tpl.sql",
		"17" => "inc/rsc/sql/tbl/help.mod_help_page.sql",
		"18" => "inc/rsc/sql/tbl/level.mod_level_page.sql",
		"19" => "inc/rsc/sql/tbl/page.mod_page.sql",
		"20" => "inc/rsc/sql/tbl/page.mod_page_acl.sql",
		"21" => "inc/rsc/sql/tbl/page.mod_page_mod_grp_ar.sql",
		"22" => "inc/rsc/sql/tbl/page.mod_page_mod_usr_ar.sql",
		"23" => "inc/rsc/sql/tbl/page.mod_page_tpl.sql",
		"24" => "web/system/img/icons/icon_mod_page.gif",
		"25" => "web/tpl/hundertelf/page/pa.tpl",
		"26" => "web/tpl/hundertelf/page/pa_ar.tpl",
		"27" => "web/tpl/hundertelf/page/pa_common.tpl",
		"28" => "web/tpl/hundertelf/page/pa_edit.tpl",
		"29" => "web/tpl/hundertelf/page/pa_enter.tpl",
		"30" => "web/tpl/hundertelf/page/pa_path.tpl",
		"31" => "web/tpl/hundertelf/page/pa_type.tpl",
		"32" => "web/tpl/hundertelf/page/pap.tpl",
		"33" => "web/tpl/hundertelf/page/tree.tpl",
		"34" => "web/tpl/hundertelf/page/tree_static.tpl",
		"35" => "web/tpl/hundertelf/search/main_searchpage.tpl",
	),
	"folders" => array(
	),
	"events" => array(
	),
	"views" => array(
	),
	"author" => "hundertelf,Thomas Schindler,Joachim Klinkhammer,Oli Blum",
	"email" => "development@hundertelf.com",
	"date" => "2004",
	"version" => "10.6",
);
?>
